### ISSUE TITLE
Conflict window: also shows location

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#101]
Case of example: a lot of rules and folders where to move files (eg pictures or graphic files, but also documents based on the content - eg. in some rules, I trigger shell scripts which check the content or the attributes of text files): in such cases when a conflict window appears, it will only show the file name but not the location (folder) where the conflict occurs. So would be nice - for sake of completeness - if the conflict window would also show the folder where the file is already present (and maybe also the source folder, since most of rules are managed by AutoFiler which automatically works in background.)

**Comment by humdingerb** [comment]
I agree. Maybe something like this, if possible:
´´´
Rule '%nameofrule%' encountered a conflict:
'%filename%' already exists at the destination.

Source: %sourcepath%
Destination: %destinationpath%
´´´

**Comment by owenca** [comment]
What should I use for multiple-line text view? BStringView displays all the text in a single line.

**Comment by humdingerb** [comment]
BTextView is made for that. \n for newlines.

**Comment by owenca** [comment]
`BTextView` won't resize to fit multiple lines of text, so I have to use multiple `BStringView`s. :(

**Comment by Giova84** [comment]
Hey @humdingerb, when this commit will be done, please ping me: so I will provide you the translations for the new entries in the conflict window :-)

**Comment by owenca** [comment]
After this PR is merged, I have one more PR to remove the date-related code along with "is before" and "is after".
