### ISSUE TITLE
Beautfy the Conflict window

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#107]
Instead of a GroupLayout, the Conflict window should use a GridLayout which allows to neatly arrange stuff in columns and rows. Here's a mockup: ![Imockup](http://img.ctrlv.in/img/17/08/07/5988858380438.png)

- I'd keep it all left-aligned with the first row spanning two columns.
- As we eventually would like to make the source and destination objects clickable, I think it's more consistent to not only use the parent paths, but the path+objects even if the file name is also mentioned explicitely in the 2nd row.
- The dates and size rows could be italicized and/or tinted slightly lighter that the source/destination path row.

Eventually, it'd be nice if the Conflict window would sport a darker vertical strip to the left and a "!" icon, like BAlerts do. (e.g. in Terminal: `alert --warning "File already exists in target folder."`

**Comment by owenca** [comment]
I have left source/target as folders so that clicking either path will bring up Tracker with the file name highlighted/selected and scrolled to the top (or center) of the Tracker window. (The clickable folder path is yet to be implemented.)

**Comment by owenca** [comment]
![conflict window](https://user-images.githubusercontent.com/6434360/29048696-d40e1fd6-7b86-11e7-8f0f-15506fcd3628.png)
