### ISSUE TITLE
Crash on ignore conflicting file when multiple rules

### ISSUE THREAD

**Issue by phoudoin** [HaikuArchives/Filer#111]
Disable "apply to first rule matching" setting.
Drop two times the same file to trigger the same rule and generate a conflict.
Select "Ignore" button.
Crash! (see bug report attached)

With "apply to first rule matching", it doesn't crash.

[Filer-4127-debug-11-08-2017-11-46-02.report.zip](https://github.com/HaikuArchives/Filer/files/1217490/Filer-4127-debug-11-08-2017-11-46-02.report.zip)

**Comment by humdingerb** [comment]
If I understand you right, I cannot reproduce. Do I get this right:
- Drop a file onto the dropzone that'll get processed, like a text file that's promptly moved to another folder.
- Drop a similarly named file onto the dropzone. The conflict window appears, you press "Skip" (what you called "Ignore"?). And crash!
Cannot reproduce the above...

**Comment by phoudoin** [comment]
Only if apply to first matching rule only setting is disabled.
I use the default rules. With an image file.

**Comment by phoudoin** [comment]
The crash happened in the IsTypeMatch of last rule the extract zip one

**Comment by owenca** [comment]
Thanks for the bug report! Do we see the same crash in v1.1.0?

**Comment by phoudoin** [comment]
X86_64 hrev51354
Build from git source.

**Comment by owenca** [comment]
Sorry. There is no conflict window in v1.1.0. However, I tried with both gcc2- and gcc5-compiled Filer/AutoFiler with 32-bit hrev51354 but couldn't reproduce the bug. Maybe it only crashes in 64-bit Haiku?

**Comment by humdingerb** [comment]
Tried in 64bit as well, still can't reproduce.

**Comment by phoudoin** [comment]
I tried again, and with text files the issue don't happened. But with an image (a PNG file taken via screenshot), it does.

**Comment by humdingerb** [comment]
Are you sure you're using the lasted version, v1.2.1? Your first crash report was from 11-08-2017...
FWIW, I still cannot reproduce, PNG or not.

**Comment by phoudoin** [comment]
v1.2.1 just built from a fresh haikuports.

**Comment by humdingerb** [comment]
Thanks to DeadYak for helping me on the bughunt!
Running a debug compiled Filer with LD_PRELOAD=libroot_debug.so was very helpful. Also, bookmarked this blog post: https://www.haiku-os.org/blog/mmlr/2010-02-08_using_malloc_debug_find_memory_related_bugs/
