### ISSUE TITLE
Untyped files (on non-BFS partitions) in the file panel

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#117]
The current state - 1a32ca2 - has some issues with the BRefsFilter with files with no MIME type, e.g. on non-BFS partitions.

I created a USB stick with 5 partitions (fat32, ntfs, ext2, ext3, ext4) and copied a ZIP.zip archive and a SCRIPT.sh script (chmod -x'ed) onto each (under Ubuntu):

**Shell command**

_Filesystem_ | _Filepanel shows_
-- | --
ext2/3/4 | ZIP.zip
fat32/ntfs | SCRIPT.sh

**Add to archive**

_Filesystem_ | _Filepanel shows_
-- | --
ext2/3/4 | ZIP.zip
fat32/ntfs | SCRIPT.sh + ZIP.zip

Under ext2/3/4 there seems to be an issue with the script not showing at all. Maybe because it's x-flag is set? Is this an issue with Haiku's ext filesystem driver itself, as the behaviour with fat32 and ntfs seems to be alright?
If so, this bug should be moved to Haiku's Trac.

----

PR #116 has proposed some changes, which would make things worse, extending the issue to refusing drag&dropped files from those partitions onto the text controls. The file panel situation after applying #116 is as follows:

**Shell command**

_Filesystem_ | _Filepanel shows_
-- | --
ext2/3/4 | nothing
fat32/ntfs | nothing

**Add to archive**

_Filesystem_ | _Filepanel shows_
-- | --
ext2/3/4 | nothing
fat32/ntfs | ZIP.zip

**Comment by humdingerb** [comment]
The "Tracker Kind shows" column above is rubbish, I've sinced removed it. I meant to say:

- on ext2/3/4 the script is recognized by Tracker as a "Be application", under fat32/ntfs as "Generic file".
- on ext2/3/4 the zip is recognized by Tracker as a "Generic file", under fat32/ntfs as "ZIP archive".

**Comment by owenca** [comment]
Filer uses the MIME type of the file to determine if it's a shell command ("text/plain"), an archive ("application/zip"), or a generic file ("application/octet-stream"). What are the MIME types of your files when Haiku recognizes them as "Be application", etc.?

I have just noticed that:

- .rsrc files are "application/octet-stream".

- .o files have Kind "Be application" and an empty MIME type. (That's probably why script files from ext2/3/4 don't show up in file panels.)

I will change the code so that files with an empty MIME type get the same treatment as generic files. Now Filer really shows too many unknown/generic files in file panels.

Maybe a good compromise would be let the file panels for Archive and Command actions be restrictive and only show text or zip files. If the user wants to use the files with generic/unknown types, the drag&drop option is available.

**Comment by humdingerb** [comment]
> Filer uses the MIME type of the file to determine if it's a shell command ("text/plain"), an archive ("application/zip"), or a generic file ("application/octet-stream"). What are the MIME types of your files when Haiku recognizes them as "Be application", etc.?

As you correctly predicted, its file type is empty.

> Maybe a good compromise would be let the file panels for Archive and Command actions be restrictive and only show text or zip files. If the user wants to use the files with generic/unknown types, the drag&drop option is available.

I don't think that's a good idea. Maybe the user isn't even aware of drag&drop and wonders why the file panel doesn't show his files while Tracker does.

> .rsrc files are "application/octet-stream".
> .o files have Kind "Be application" and an empty MIME type. (That's probably why script files from ext2/3/4 don't show up in file panels.)
> I will change the code so that files with an empty MIME type get the same treatment as generic files. Now Filer really shows too many unknown/generic files in file panels.

Good. It's better to show too many files in the filtered file panels than too few. Also, most probably the scripts/archives the user sets as actions aren't in a location where there are .o or .rsrc files or even untyped generic files.
Alternatively, we could abandon filtered file pnels altogether, but I think it helps more to filter out the definitely unwanted files than showing sometimes a few untyped/generic files alongside.

**Comment by owenca** [comment]
Does PR #116 fix this issue?

**Comment by humdingerb** [comment]
Nope. I think it's a problem of what Haiku's file systems report. The behaviour described in those tables is still there, after #116 was merged.

**Comment by owenca** [comment]
Hmm, I have to conclude that the MIME types of these files are neither empty nor generic ("application/octet-stream"). Can you try https://github.com/HaikuArchives/Filer/compare/master...owenca:master to see what these mysterious MIME types are?

**Comment by humdingerb** [comment]
Unfortunately, your code changes only print the MIME types when the file panel is opened the first time, which is always at /boot/home. Switching to a foreign-fs partition on my stick doesn't output anything.

**Comment by humdingerb** [comment]
I hardcoded the path and did a SetPanelDirectory() when the filepanel is created. Here's the output:

**Shell command**

_Filesystem_ | _Filepanel shows_ | Terminal output
-- | -- | --
ext2/3/4 | ZIP.zip | SCRIPT.sh: application/x-vnd.Be-elfexecutable
fat32/ntfs | SCRIPT.sh | ZIP.zip: application/zip

**Add to archive**

_Filesystem_ | _Filepanel shows_ | Terminal output
-- | -- | --
ext2/3/4 | ZIP.zip | SCRIPT.sh: application/x-vnd.Be-elfexecutable
fat32/ntfs | SCRIPT.sh + ZIP.zip | nothing

**Comment by owenca** [comment]
> Unfortunately, your code changes only print the MIME types when the file panel is opened the first time

Weird. It works for me when I open the file panel for "Add to archive" or "Shell command", the only cases Filer looks for a particular MIME type. The extra code just prints the files that won't appear in file panel, including whenever the current folder changes in the panel.

> Here's the output

From your tables, I can deduce the MIME types:

Filesystem | SCRIPT.sh | ZIP.zip
-- | -- | --
ext2/3/4 | application/x-vnd.Be-elfexecutable | application/octet-stream
fat32/ntfs | application/octet-stream | application/zip

So the elf executable is a "new" MIME type for Filer. I have added it to the MIME types of "Shell command". Can you try the updated commit?

**Comment by owenca** [comment]
The first row of your first table will look like this now:

**Shell command**

Filesystem | Filepanel shows | Terminal output
-- | -- | --
ext2/3/4 | SCRIPT.sh + ZIP.zip | nothing

There will be no change in the second row, and the other table will stay the same.

**Comment by humdingerb** [comment]
Yep. BTW, I was confused by the missing output for fat32 back then. It all works as expected, and I do see the output when trying with ext2, for example. I just wasn't prepared to "no output" and accidentally always tried with dropping the fat32 volume into the file panel and therefore assumed something was wrong... :)
