### ISSUE TITLE
Abstract test/action names from labels

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#12]
The labels of tests/actions ("Move to..." etc.) use the strings saved into the rules.  
Therefore, labels can't be renamed without the stored rules becoming outdated. This also prevents localizing Filer.

**Comment by owenca** [comment]
After discussing this issue with waddlesplash, PulkoMandy, and others, I think it has to wait until https://dev.haiku-os.org/ticket/13572#ticket is resolved. Maybe try to run Filer on a German or French Haiku to see what happens?

**Comment by humdingerb** [comment]
I think, as long as Haiku itself doesn't come up with a solution to localized custom attributes, it's OK for Filer not to localize MIME types and more specifically their attributes.
It'd suffice to have the actions themselves localizable, e.g. "Move to folder..." etc. This wasn't possible before, because the old button lables were also used as e.g. action when saving a rule. IIRC...

**Comment by owenca** [comment]
I will look into localizing the Do box then. Wouldn't it look odd if the When box were in English while the Do box were in another language?

**Comment by owenca** [comment]
It seems that the mode menu (the "is" button) in the When box is not dependent on the MIME database, so it's possible to localize it plus the action menu in the Do box. I will work on this issue next.

**Comment by humdingerb** [comment]
> Wouldn't it look odd if the When box were in English while the Do box were in another language?

Sure, but we see these issues wherever custom attributes appear in the GUI, just set another locale and look at the FileTypes preferences... Having the rest of the GUI localized is a good first step.

**Comment by owenca** [comment]
To localize the menus in TestView and ActionView, simply translate the string tables (sTestTypes, sModeTypes, and sActions) in RuleRunner.cpp.

**Comment by humdingerb** [comment]
I did quickly hard-code the German strings there (your PR #41). They do show up when creating a new rule, but the existing rules still show the English strings. I'm not sure how those sqlite rules are formatted, but I guess it'll too have to be abstracted from the locale.
Also, can the current (English) format be automatically converted when encountered? People may have a number of complex rules that they wouldn't want to lose/re-create.

**Comment by owenca** [comment]
> but the existing rules still show the English strings. I'm not sure how those sqlite rules are formatted, but I guess it'll too have to be abstracted from the locale.
Yes, the pre-existing English rules will remain in English, and I don't think they would still work in a different locale. However, I think the sqlite rules will still be in SQL (in English) regardless of the locale.

> can the current (English) format be automatically converted when encountered?
No, and I don't know if it's possible. If B_TRANSLATE is a macro and can only handle string literals but not variables, then I don't see a way to make it work.

**Comment by owenca** [comment]
Well, I have just thought of a way that might work. It's similar to the way I used to make PR [#18](https://github.com/HaikuArchives/Filer/pull/18) backward compatible but would be more complicated.

**Comment by humdingerb** [comment]
Being locale independend would be very desirable. So, saving "ACTION_MOVE" instead of "Move to folder…" would be good.
Alternatively, getting rid of sqlite and using something like one flattened BMessage per rule would be kinda nice too, I guess.
Tell me if I should merge your PR as is, so you cancontinue to develop in the direction you think best.

**Comment by owenca** [comment]
Please merge the PR if it works (albeit not being backward compatible, and I will create a separate issue so that you can close this one). I don't think the menu labels like "Move to folder..." are actually read from and saved into the rules except for those that are generated from the mime info (which doesn't support localization yet).

As to SQLite, it's a totally new beast for me, and I still have little clue how it works and how it's used by Filer. As much as I have worked on Filer, I still can't see the forest for the trees.

**Comment by scottmc** [comment]
Here's a tutorial on SQL lite that might help you understand it better: https://www.tutorialspoint.com/sqlite/

**Comment by owenca** [comment]
Thanks, scottmc! I skimmed through it before when working on PR #18. It's more for SQLite users than developers as I recall, but I will definitely revisit it.

**Comment by owenca** [comment]
humdinger, you are right that the action names (and also the mode names) are stored into the rules. Your suggestion of saving the action type (a 4-byte integer) instead is superior but would make fixing issue #42 (just fixed in PR #43) very difficult if not impossible.

**Comment by owenca** [comment]
Now I think saving the `enum` integers (`TEST_TYPE`, `MODE_IS`, `ACTION_MOVE`, etc.) instead of the string names is feasible, although not very easy. I will give it a shot after PR #43 is merged.

**Comment by humdingerb** [comment]
This was solved with Owenca's recent PRs.
