### ISSUE TITLE
"Filer" silently overwrite/replace existing files.

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#15]
I have a rule called "Store pictures in my Pictures folder"; so eg, when I take a screenshot named "Screenshot1.png" which is saved on the Desktop, this file will be automatically moved in my pics folder by Autofiler.
Then, If i take another different file called "Screenshot1.png" and I place it on my Desktop, AutoFiler will move this file inside the pics folder, overwriting the "Screenshot1.png" which was previously present inside the pics folder.

**Comment by humdingerb** [comment]
In case of conflicting filenames, we have these options:
* Overwrite existing file
* Rename the new file
* Don't process the file
* Ask the user
The behaviour should be defined as part of every rule that deals with copy/move/rename with a section "Behaviour for conflicting files:" with a radio list of the above options.

In case of "Ask the user", a window will pop up.
Ideally, it should show info on the old and new file side-by-side (e.g. icon (double-click could open the file), filename, mime type, size, last modified) and these radio options:
* Overwrite existing <filename>
* Rename new file to <new filename>
* Don't process the file
and a checkmark
* Use this choice for all files in this batch

The checkmark avoids having the window pop up again and again, and remembers the choice for all the files in the current batch of files.

Implementing a solution can be a bit complicated. Filer and AutoFiler may have to process many files in a batch. Filer is then invoked on each file in that batch. We have to keep that in mind when we "use this choice for all files in this batch".

**Comment by owenca** [comment]
Filer launches another Filer:
https://github.com/HaikuArchives/Filer/blob/master/sources/DropZoneTab.cpp#L155
https://github.com/HaikuArchives/Filer/blob/master/sources/FilerDefs.h#L12

This prevents me from creating a modal popup window from within the launched Filer although BAlert sort of works. (The alert is not modal relative to the Filer tab view.) Is there anything to do about this problem?

**Comment by humdingerb** [comment]
Yes, if I see this right, dropped files are fed serially to a newly created, then destroyed Filer instance. A popped up dialog will block only that affected Filer instance, thereby blocking the processing of the following files of the drop. It wouldn't block the Filer main window, and why would it.

Question is, how to deal with that checkmark that will have to chosen action remembered for all files of this one drop? I alluded to that in the last paragraphs of my initial comment to this ticket. Not sure how to solve it... maybe some communication with the "main app"? But how to deal with a bunch of files being opened with Filer via "Open with..." in Tracker?

**Comment by owenca** [comment]
Thanks! I had already created a BAlert-like modeless window that would stay on the screen until an action button is pressed, using a semaphore. (I confused modal window with having the window stay on the screen.) I will learn to do it the way in "what to do" 3-5 above when I am done.

I decided that it would be better not mixing renaming with move/copy after analyzing the existing code. So I use two action buttons (Overwrite and Skip) along with a checkbox "Don't ask again" in the popup dialog. If the user wants to rename conflicting files, he can always click on the checkbox and press Skip and then run a Rename rule.

MoveAction() and CopyAction() in RuleRunner.cpp are almost identical except for two places (calling MoveFile() vs CopyFile() and printing "Moved" vs "Copied"), so I refactored the code and added the logic to handle "Don't ask again". I will create a PR shortly.

I scanned through the HIG. It has lots of good design tips!

**Comment by humdingerb** [comment]
> If the user wants to rename conflicting files, he can always click on the checkbox and press Skip and then run a Rename rule.

Is that a good idea? It sure would be more convenient to have only one rule that copies a file somewhere and have Filer deal with possible renaming when there are conflicts. Otherwise the user has to come up with a quite a bit more complicated rule that deals with renaming+copying. And he has to invoke two runs instead of one.

**Comment by owenca** [comment]
I feel that letting the user rename the files while moving/copying would make things overly complicated. I thought about giving him two options: rename the existing file by appending .old or rename the new file by appending .new. Then I would have to check if the .old or .new file already exists. Another possibility is to append "(1)", "(2)", etc. I just don't feel very confident about all this.

**Comment by owenca** [comment]
Here is the PR: https://github.com/HaikuArchives/Filer/pull/16

**Comment by humdingerb** [comment]
Yeah, I know it's complicated. :)
Would be much easier if somehow Filer could used Tracker's functionality of auto-renaming (adding (1), (2),...).
I'd say this is one big step in the right direction.

**Comment by owenca** [comment]
Since AutoFiler is launching Filer for every file, I will see if it can be changed to launching Filer only once for a batch of files. After that, we can try to add a Rename button to the window if it can be made to work well.

**Comment by Giova84** [comment]
Hi Humdinger, I've seen that you committed the fix from owenca, 11 days ago:
f7cd9b60bd6ab7968aa0b54249e2f8443f055e46

So, this ticket can be closed? I've built Filer from the last source and seems to work ok.

**Comment by humdingerb** [comment]
Yep.
@owenca: feel free to create new issues for the things still missing, even if you yourself won't work on it (immediately). Like the optics of the conflict window etc.

**Comment by owenca** [comment]
Will do.
