### ISSUE TITLE
Enhancement: add the ability to just disable rules

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#17]
Sometimes could be useful to disable some "rules", but actually is only possible by deleting them: in a case of a complex rule, we will have to reinsert again every part of a "formula" which composes the rule.
So would be nice to add a "enable/disable" option for every rule.

**Comment by owenca** [comment]
I guess the simplest way, from the GUI point of view, is to insert a Disable button between Edit and Remove in the Rules tab. The rules will be grayed out when disabled. What do you think?

**Comment by humdingerb** [comment]
Sounds good. The button label should toggle between "Disable" and "Enable" depending on the selected entry.
Maybe even add a "-- disabled" after the rule name in the list, to make it even more obvious.

With 4 buttons below the list, the window gets quite wide. I suggest switching their location with the "Move up/down" buttons, i.e. the Move buttons below, the Add/Edit/etc. vertically arranged to the right of the list.

**Comment by owenca** [comment]
Is there a way to delete the above links to the intermediate (and squashed) commits? Please use the [PR](https://github.com/HaikuArchives/Filer/pull/18) link instead.

**Comment by humdingerb** [comment]
Fixed with #18 bd41f3d537298f9d6a8d0a1dccf2b49e2d6b0aaf. Thanks owenca!

**Comment by Giova84** [comment]
I'd want to say a big thank you to owenca for his good work and improvements on this useful application!
