### ISSUE TITLE
Enhancement: enable the Open button in the "Filer: Open" window even if nothing is selected.

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#20]
If you click on the Add... button from the AutoFiler tab, you will see that the Open button in the "Filer: Open" window is disabled. It should be enabled so that you can add the home folder.

**Comment by humdingerb** [comment]
Yes. This is a shortcoming of the BeAPI, see [ticket #8116](https://dev.haiku-os.org/ticket/8116).
It can be solved like it's done for Expander.

**Comment by owenca** [comment]
Ok. So close it?

**Comment by humdingerb** [comment]
It doesn't feel like the API is going to change in a hurry...
It looks like Filer could do a similar thing as Expander and add a third custom button to the file panel to "Open {current folder}.

**Comment by owenca** [comment]
I scanned through the FilePanel and Expander code and think it's doable. Which interface though?
1. Always enable the Open button and open the top folder shown in the upper left corner if nothing is selected.
2. Use a dynamic label for the always enabled Open button: "Open {top folder}" or " Open {selected folder}"
3. Add an always enabled button: "Open {top folder}"

**Comment by humdingerb** [comment]
I like 2) best.
If/when the user is able to add more than one folder, there's the additional case for "Open {number of folders} folders".

**Comment by owenca** [comment]
I experimented with 2) and it didn't work well. First, the Open button is not layout aware (or BFilePanel does not support layout?):
![open home](https://cloud.githubusercontent.com/assets/6434360/25073651/a887ec6a-229f-11e7-9bb3-09eb2f88ffe8.png)
Even if we fix that, the Open button would expand and contract depending on the folder name, and the Cancel button would move back and forth along with it. If the folder name is very long, we would have a very wide Open button.

I will try 1), which probably doesn't need to create a subclass (e.g., FilerFilePanel). Other options are 3) or adding an Open button next to popup menu button (upper left corner) for the parent folder. Both would require inheriting from BFilePanel.

**Comment by humdingerb** [comment]
No idea about the layouting of the buttons in BFilePanel...
And you got a point with jumping buttons because of changing labels, haven't thought of that.
All that considered, I now tend more to solution 1). :)

**Comment by owenca** [comment]
Solution 1) can't be implemented because the Add button can't be kept enabled. It's disabled by a BContainerWindow a couple of layers inside the BFielPanel when no files are selected in the panel. I will try solution 3) next.

**Comment by humdingerb** [comment]
> Solution 1) can't be implemented because the Add button can't be kept enabled. It's disabled by a BContainerWindow a couple of layers inside the BFielPanel when no files are selected in the panel.
Too bad. I guess it's not trivial to fix in the Haiku source? Generally, any "Open directory" file panel should open the current folder if none is selected...

**Comment by owenca** [comment]
It's very easy to fix the Haiku source code (if the current behavior of the default "Open" button is an oversight instead of by design). What's the process of proposing the change?

**Comment by owenca** [comment]
By the way, BFilePanel does not use the layout management.

**Comment by humdingerb** [comment]
> It's very easy to fix the Haiku source code (if the current behavior of the default "Open" button is an oversight instead of by design). What's the process of proposing the change?

You create a patch as described at https://dev.haiku-os.org/wiki/CodingGuidelines/SubmittingPatches then create a ticket at the Haiku bugtracker with a decription what was wrong and how you've fixed it and attach the patch.

You can also add a ticket with the file panel screenshots showing the problems.

**Comment by humdingerb** [comment]
WRT the artifacts, there's also https://dev.haiku-os.org/ticket/12887

**Comment by owenca** [comment]
I think it's a layout issue: the Cancel button and the default Select button are not at the bottom next to the "Select {current}" button. I occasionally had a similar problem with the Add button in the "AutoFiler: Add" window. The problem is gone when I move the BFilePanel::SetButtonLabel() from the constructor to MessageReceived()...

**Comment by humdingerb** [comment]
No idea if that's a bug or a feature... :)

**Comment by owenca** [comment]
fixed in hrev51155
