### ISSUE TITLE
Alphabetically sort the monitored AutoFiler folders

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#23]
Whenever a folder is added, removed or edited on the AutoFiler tab, the list of monitored folders should be alphabetically sorted.

**Comment by owenca** [comment]
Fixed in https://github.com/HaikuArchives/Filer/pull/22.

Unfortunately, when listing issue numbers one per line in the commit message, I didn't add a blank space before the sharp sign #, and the list of issues got commented out.
