### ISSUE TITLE
Lose the Edit button in the AutoFiler tab?

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#25]
The Edit button in the AutoFiler tab is superfluous and problematic. It opens a file panel that asks me to "choose" a subfolder of the folder that is being "edited". If the folder has no subfolders, I am given an empty (sub)folder list with nothing to choose from.

"Edit" right now actually means "Choose" another folder instead. Why not just remove the folder and then add a new one (or ones)?

**Comment by humdingerb** [comment]
You got a good point there... :+1:

A shame you didn't notice that earlier, would've saved you some work, eh? :)

**Comment by owenca** [comment]
Yeah. I wish I had used Filer more before diving into fixing an issue.
