### ISSUE TITLE
"Edit rule": some windows are narrow and cannot be horizontally resized

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#30]
I built filer from the last commit (when the Layout management was introduced) and i discovered that some "edit rule" windows of some rules are narrow and cannot be horizontally resized. Eg this one, which I cannot resize horizontally:
![Edit rule window narrow](http://funkyimg.com/i/2ueuQ.png)

I said "some rules" because not all suffer of the same issue: **Seems** that if in the "Do" section, the action name is shorter (like in the above case "Delete")  than the "Remove" button I cannot resize the window.
Instead, ** seems** that if the action name is longer then "Remove" (eg "Move to folder") I am able to horizontally resize the edit rule window.
See:
![Edit rule window OK](http://funkyimg.com/i/2uevy.png)

**Comment by Giova84** [comment]
Sorry: I am on QupZilla and I am unable to edit my previous comment :-[

Obviously, as seen in the first screenshot, the "Delete" button is not shorter than the "Remove" button, but seems equal in terms of dimensions; however is misaligned.

**Comment by humdingerb** [comment]
This seems to be solved in @owenca's PR #29 .
Since it's using a BMenuField instead of a BButton for  "Delete" etc., the window keeps being resizable.

**Comment by owenca** [comment]
Giova84: do you still have this problem?

**Comment by Giova84** [comment]
Owenca: I would be glad to test your changes; however in the commits page ( https://github.com/HaikuArchives/Filer/commits/master ) at the moment I don't see your last changes: I miss something? I run Filer compiled some days ago from "master". Sorry, but I'm not confidential with GitHub..

**Comment by Giova84** [comment]
Sorry for the noise: now I see a commit from today (Jun 19, 2017); I'm going to compile Filer.

**Comment by Giova84** [comment]
Sorry again: on QupZilla I am unable to edit my previous comments...
I compiled filer and now I am able to properly resize every "Edit rule" window.
Good work, Owenca!

**Comment by humdingerb** [comment]
Indeed! Thanks for confirming, Giovanni.
