### ISSUE TITLE
"Edit rule window": in some rules the "Remove" button is disabled

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#31]
See the following screenshot: maybe I'd like to replace the "Do" action, or change the condition in the "When" section, but the "Remove" button is disabled:
!["Remove" buttons disabled](https://camo.githubusercontent.com/a1313fdf01a7b3d8f977dafa756fd98a01b244e5/687474703a2f2f66756e6b79696d672e636f6d2f692f32756576792e706e67)

Instead, in some other rules, the remove button is enabled:
!["Remove" buttons enabled](https://camo.githubusercontent.com/f90f42266b5fbc7f3c443f48a793bd9ef9929198/687474703a2f2f66756e6b79696d672e636f6d2f692f32756575512e706e67)

**Comment by humdingerb** [comment]
Let's wait on Owenca's opinion, but I don't think this is a bug. There always has to be at least one "When" condition and one "Do" action. You can never remove the last remaining condition/action, therefore the "Remove" button gets disabled.

**Comment by Giova84** [comment]
Well, however if I add a second condition or action, and so the "Remove" button becom enabled, I can just remove the last condition or action. So, in this case, if I want to remove a previous condition/action, I have to make again the rule from scratch

**Comment by humdingerb** [comment]
Yes. This actually is discussen in issue #11 . I'll close this one then.
