### ISSUE TITLE
Add icon-button to specific actions to open file dialogs

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#32]
Certain actions could do with a file dialog to enter folder paths. It could be added in front of the text control that holds the path.

An 'Open' 'Directory' file dialog for:
* Move to folder...
* Copy to folder...

A 'Save' File dialog for:
* Add to archive...

An 'Open' 'File' dialog for:
* Shell command...

**Comment by owenca** [comment]
I need to learn how to implement an icon button first. What documentation and existing code should I look at?

**Comment by humdingerb** [comment]
Never done it myself, but it looks quite straight forward, see [BButton's SetIcon()](https://www.haiku-os.org/docs/api/classBButton.html#af0e997793337926bf7d026868f4d684b).
How to get to the icon data from the ressources, see GetIcon() of Filer's HelpTab.

Apps like BePDF and Koder use [this I-O-M file](https://github.com/HaikuArchives/BePDF/blob/master/bepdf/graphics/OPEN_FILE.iom). Filer should too, to fit it.

**Comment by owenca** [comment]
Thanks! I thought there was an undocumented class BIconButton derived from BButton because the icon buttons are much smaller than a regular button.

**Comment by humdingerb** [comment]
Yes, I think so. I expect you can use a smaller button, like you did with the +/- buttons in the rules window. Here's an example of SetIcon() in the Haiku source: http://xref.plausible.coop/source/xref/haiku/src/servers/print/ConfigWindow.cpp#351

**Comment by owenca** [comment]
> A 'Save' File dialog for:
> - Add to archive

I think it should be an Open file panel. A Save file panel has an extra text control for editing the name of the selected file and is often for "Save as...".

**Comment by humdingerb** [comment]
Indeed. That suggestion was from before we (or I...) realized that Filer always deals with single files and its file name determines the ZIP archive's name. So, Open panel it is.

**Comment by humdingerb** [comment]
Merged!
