### ISSUE TITLE
Make conditions/actions' text control drag&drop aware

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#33]
Conditions and actions could be aware of dropped files onto their path/file text control.
E.g., a folder/file dropped on the text control of

* When|Type inserts its MIME type
* When|Name inserts its name
* When|Location inserts its path
* Do|Move to folder...  inserts its path
* Do|Rename to...  inserts its name
etc.

**Comment by owenca** [comment]
Is the archive in the "Move to archive" action a folder or a file?

**Comment by humdingerb** [comment]
As ArchiveAction() just calls "zip", it's a file name that's expected.

**Comment by owenca** [comment]
I see. Thanks!

**Comment by owenca** [comment]
Close this one?

**Comment by humdingerb** [comment]
Indeed.
