### ISSUE TITLE
Only the last row in the "Edit rule" window can be removed.

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#35]
Replace the Add/Remove buttons with one +/- button per row so that any row can be removed and a new row can be added below any row. (See issue #11.)

**Comment by owenca** [comment]
It seems there is a bug in the layout builder. I set the max size for the "-" button, but the layout builder still uses the default button size:

![minus](https://user-images.githubusercontent.com/6434360/27398015-3438ca26-566d-11e7-9d16-80c6e74df189.png)

**Comment by humdingerb** [comment]
Without having tried it, maybe add a high weight, like 100.0, to the text control when .Add'ing it.

**Comment by humdingerb** [comment]
I commented on your https://github.com/owenca/Filer/commit/843a74e7244c97d3e3bb51c339a67623554e351d

I cheated by looking at the "Repositories" prefs code... :)

**Comment by owenca** [comment]
Thanks! And the Haiku Book really needs to be fixed. Such a basic omission caused hours of frustration and your time looking into it!!
![setexplicitysize missing](https://user-images.githubusercontent.com/6434360/27495945-e1050318-5808-11e7-9503-4d53b6c128c5.png)

**Comment by owenca** [comment]
Just to be clear, I was talking about the `BView::SetExplicitSize` function.

**Comment by humdingerb** [comment]
Yes. The API docs are still incomplete and could use some love. Patches in that area are very welcome... :)
I do see, of course, that it needs quite some insight wrt the workings of the layout management to be able to contribute there. I'm surely not up to it...

**Comment by humdingerb** [comment]
Owenca added +/- buttons to all rows. So, fixed.
