### ISSUE TITLE
Test mode menu doesn't work when test type is Attribute, e.g., "Query : Formula".

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#50]
This is a bug in v1.1.0:
![mode](https://user-images.githubusercontent.com/6434360/27773693-5b9afdee-5f34-11e7-9f1e-0b9d4d3f6669.png)
Clicking on the mode button (i.e., "starts with" in the above screenshot) has no effect; it should bring up the "is, is not, starts with, ..." popup menu:
![mode menu](https://user-images.githubusercontent.com/6434360/27773746-76f2de44-5f35-11e7-8373-8e13efe7ed1c.png)

**Comment by humdingerb** [comment]
Fixed with PR #54 . Thanks!
