### ISSUE TITLE
Backward compatibility of FilerRules file formats: remove SupportLocale flag?

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#51]
We have the old format from v1.1.0, the newer format with the enabled/disabled flag for each rule, and the newest format that replaces string names for test (e.g., "Type"), mode (e.g., "is"), and action (e.g., "Move to folder...") with integer codes (TEST_TYPE, MODE_IS, and ACTION_MOVE, respectively). Because the newer formats are post-v1.1.0 and from unreleased versions of Filer, it's probably sufficient to make the newest format compatible with the v1.1.0 format and ignore all the other formats in between. (There were intermediate formats that only converted some of the test, mode, and action strings to integers.) If so, we need to remove the SupportLocale flag from Filer_settings file.

**Comment by humdingerb** [comment]
Definitely. Only the last v1.1.0 rule format should be considered for conversion to the new format.

**Comment by humdingerb** [comment]
Fixed with PR #53. Thanks, Owenca!
