### ISSUE TITLE
Localize GUI.

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#55]
Localize GUI so that Filer can be used in non-English locales.

**Comment by owenca** [comment]
I have localized all GUI but AutoFiler Tab in PR #58. I will create a new en.catkeys after localizing AutoFiler Tab.

One question: can I safely remove [MouseDown() and ShowPopUPMenu()](https://github.com/owenca/Filer/blob/master/sources/DropZoneTab.cpp#L179)? I can't trigger the popup menu with right-click.

**Comment by humdingerb** [comment]
> One question: can I safely remove MouseDown() and ShowPopUPMenu()? I can't trigger the popup menu with right-click.

No, they are still needed. The context menu only shows if you invoke it on a replicated drop zone.

**Comment by humdingerb** [comment]
Works here. Did you actually drag the replicant handle onto the desktop and right-click on it there?

**Comment by owenca** [comment]
No. I thought the window was the replicant! Now I can see the popup menu and the about window.

Why doesn't it have the handle directly at the corner of the drop zone view in the tab like ActivityMonitor? Then we can remove the replicant button.

**Comment by humdingerb** [comment]
The reason I went with that admittedly bit awkward way is that you cannot make the Filer window arbitrarily small. You may only want a relatively small area on the Desktop taken by the replicant and ATM replicants cannot be resized after being placed in a shelf.
Coding the GUI to be able to resize the DropZone within the window was too intimidating for me... :)

**Comment by owenca** [comment]
Now fixed.

**Comment by humdingerb** [comment]
Thanks. I'll be updating the German catkeys soon.
