### ISSUE TITLE
Logic of "Size" test is reversed

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#62]
It looks like the logic for the "Size" tests are reversed, see https://github.com/HaikuArchives/Filer/blob/master/sources/RuleRunner.cpp#L612

The variable names "fromsize" and "tosize" aren't that great IMO...

**Comment by owenca** [comment]
I think you are right. It seems that fromsize means the size from the text control and tosize is the size of the file. They should be renamed.

**Comment by humdingerb** [comment]
Fixed with #65 . Thanks!
