### ISSUE TITLE
"Size" test could be more sophisticated

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#63]
Currently the user has to enter the file size in bytes. It'd be nice if the test could look for "k" or "K", "m" or "M" and "g" or "G" to use kilo, mega, giga bytes in its comparisson.

Until then, the "Size" test should be more specifically named "Size (in bytes)", I guess.

**Comment by humdingerb** [comment]
If at all possible, the size unit would best be done with a dropdown menu after the text control showing localized "KiB", "MiB", "GiB" and, why not, "TiB".

**Comment by owenca** [comment]
Good idea! I have created a related issue #64.

**Comment by owenca** [comment]
It's half way there, but I might not be able to work on Haiku for a few days.
![1of2](https://user-images.githubusercontent.com/6434360/28246354-0fa20fe2-69cd-11e7-8233-4bf35a069cee.png)
![2of2](https://user-images.githubusercontent.com/6434360/28246355-0fa34b32-69cd-11e7-8061-0a8c29b38967.png)

**Comment by owenca** [comment]
I have created a follow-up issue (#74). Close this one?

**Comment by humdingerb** [comment]
Right, thanks.
