### ISSUE TITLE
The text control entry for the Size test should only allow numbers to be entered.

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#64]
Only decimal digits 0-9 and the decimal point should be allowed in the text control for the Size test.

**Comment by humdingerb** [comment]
I expect you already know about [DisallowChar()](https://www.haiku-os.org/legacy-docs/bebook/BTextView.html#BTextView_DisallowChar).

**Comment by owenca** [comment]
No, I didn't. Thanks for the tip! I tried with `BView::KeyDown` but couldn't get it to work. I will use DisallowChar() next.

**Comment by humdingerb** [comment]
I did something similar in [Clipdinger's settings window](https://github.com/humdingerb/clipdinger/blob/master/SettingsWindow.cpp#L197)

**Comment by owenca** [comment]
Created issue #74 for fractional numbers so that this one can be closed.
