### ISSUE TITLE
Add support for archiving a single file with its own archive file.

### ISSUE THREAD

**Issue by owenca** [HaikuArchives/Filer#66]
From humdingerb:
> I see a valid use case for providing a folder where archives are stored: Say you wait for a log file to grow to 5 MiB, then zip it up and put it in a folder. The user generally might want to just have single files archived as single-file-name.zip.

Here is a proposed specification:

- If the user enters (manually or using drag&drop) the path name of an existing folder, the path name of the archive file passed to the zip command will be the path name of the folder + "/" + the name of the file processed by Filer.

- Otherwise, the path name of the archive file passed to zip will be exactly as what the user enters.

**Comment by owenca** [comment]
Trailing "/" should be removed before passing to zip to prevent creating an archive file named ".zip", which is a hidden file and doesn't make sense.

**Comment by owenca** [comment]
Actually, there is no need to remove the trailing "/". It's an indication that the user wants the path name to be the folder that the archive file will reside in–hence the updated commit.

**Comment by humdingerb** [comment]
Merged in #68. Thanks!
