### ISSUE TITLE
The "Filer" executable won't run

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#71]
I'm building Filer time after time, to check the various improvements which are made.
Until last week everything worked fine. Now, since  the commit 3e99669eb365e7572c4caffde6ebbaa15c0f9e37 when I attempt to launch the "Filer" executable, it doesn't start. If i launch it from a terminal window, all that i see is:

```
[baron@haikubox] # Filer
Abort
Abort
[baron@haikubox] #
```

Please notice that I'm running the executable which is builded with the debug flag (the one which is 6.02 MiB in size), but I don't see any debug message in the output.

I miss something?

**Comment by humdingerb** [comment]
Thanks for testing, Giovanni. Owen has made fantastic progress! :)

You have to remove your rules/settings. Filer stays compatible to (or rather converts) rules and settings from the last released Filer, but not to the work in progress since then.
So if you experiment with WIP builds, it's best to keep old-release-Filer rules around to start with.

**Comment by Giova84** [comment]
I agree: there are fantastic and very useful progresses!
I suspect, in fact, that the "culprit" was the  current setting file.
Well: I have a lot of Filer's rules: I must make them again from scratch, if in the next release this will be changed or can I keep the current rules (and back to the previous executable)? I mean: in the next release the current way to keep the rules will be the same or I have to prepare for the future? :-)

I'd like to use Filer with the current improvements.

Would be nice to implement a way to export the rules (all or individual), also to import them in another installation of Haiku.

Thank you!

**Comment by humdingerb** [comment]
The next Filer release will definitely work with the rules/setting of the last release, v1.1.0.
So, best would be to install the old Filer v1.1.0 and create the rules you need with that. Make a backup of those rules. Then keep building and using a current Filer. When you find that a new version of Filer can't deal with the rules/settings, revert them to your backed-up old ones.

I don't think im/exporting rules is a pressing feature. You can share all rules by sharing ~/config/settings/Filer/FilerRules. Not sure importing individual rules is that common to add that feature. Just share a screenshot of the rule and have them do a bit of typing... :)

**Comment by humdingerb** [comment]
That said, if Owenca wants to work on that... :)
Might be done as easily as accepting a dropped FilerRules onto the RulesTab and add those to the existing rules. Have the user remove the rules he doesn't want...
Think about keeping the GUI simple...

**Comment by Giova84** [comment]
You have been very clear, thank you!

About the suggested feature of export/import rules: I had in mind the ability of Haiku's applications: look, eg, at StyledEdit and ShowImage: you can make copies of text and images just by a simple drag and drop :-)
However I agree with you about the fact that is not a pressing feature.

**Comment by owenca** [comment]
Giova84:

> Until last week everything worked fine. Now, since the commit 3e99669 when I attempt to launch the "Filer" executable, it doesn't start.

What's the latest commit that worked for you? I might be able to get your rules back for you by adding some code to Filer, probably only in the debug version.

> Please notice that I'm running the executable which is builded with the debug flag (the one which is 6.02 MiB in size), but I don't see any debug message in the output.

The Abort error messages are most likely from SQLite. (humdinger had the same problem.) Can you upload the settings file FilerRules? I can add some error checking and printing code to let Filer abort more gracefully.

**Comment by Giova84** [comment]
> What's the latest commit that worked for you? I might be able to get your rules back for you by adding some code to Filer, probably only in the debug version.

15e90218cb0b192c98d3e783007b3e29e9ca34a6

Please notice that in this commit all my old rules were recognized, but I had to "refine" some of them. Eg, some actions which included "When location is" were reset to "When type is", so I "refined" these rules in that way.

> The Abort error messages are most likely from SQLite. (humdinger had the same problem.) Can you upload the settings file FilerRules? I can add some error checking and printing code to let Filer abort more gracefully.

I fear that is too late:
I rewritten again my Filer's rules. So, at least for me, doesn't matter; now Humdinger has pointed me how to behave :-)

Anyway: many thanks for your good work and for your time which you devote to this useful application!

**Comment by owenca** [comment]
> Eg, some actions which included "When location is" were reset to "When type is"

It shouldn't be reset by Filer. If you still have this problem, please create a new issue and attach the settings file so that it can be fixed.

> I rewritten again my Filer's rules.

I have found a simple fix, but if it's no longer needed, I will not change the code so that Filer can run a teeny bit faster. :)
