### ISSUE TITLE
RulesTab: Use -/+ buttons

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#78]
As there are + and - buttons in the "Edit rule" window, we could exchange the "Add..." and "Remove" buttons in the RuleTab for "-" and "+". That visually compacts the widgets as there's be only 3 rows of buttons beside the list.

Theoretically, it could even cut down the minimal window height, were it not for the problematic text view in the HelpTab...

**Comment by owenca** [comment]
The exactly same pair of -/+ buttons from the "Edit rule" window? Then perhaps the "Move up" and "Move down" buttons can be replaced with a pair of up/down arrow buttons so that all the buttons can be placed on the right side and there will be 4 rows of them.

**Comment by humdingerb** [comment]
Yes. I'd make the buttons full-size. If there aren't suitable utf characters for the arrows, we may have to use icons.

**Comment by owenca** [comment]
I won't add an alert for deleting a rule, so we can close this issue now.

**Comment by humdingerb** [comment]
OK.
