### ISSUE TITLE
Change file panel titles

### ISSUE THREAD

**Issue by humdingerb** [HaikuArchives/Filer#90]
The file panel titles of the rules edit window should be changed:

Test:
"Filer: Choose file with same: {test-pop-up-label}"

Action:
"Filer: {action-pop-up-label}

**Comment by owenca** [comment]
Change the "Open" button in file panel to "Choose" for tests like for AutoFiler tab? What label to use for actions?

**Comment by humdingerb** [comment]
I guess "Choose" is good for both tests and action. Good catch.

**Comment by owenca** [comment]
> "Filer: Choose file with same: {test-pop-up-label}"

I have used ...Choose folder with same... for Location.

**Comment by owenca** [comment]
I have just noticed that ...Choose file/folder with same Type/Name/... would confuse the user into thinking the mode is "is" while it can be "is not", "starts with", etc. I will change "with same" to "for", so the test panel title would be ...Choose file for Type..., ...Choose folder for Location..., and so on.

**Comment by humdingerb** [comment]
You're quite right. Thanks!

**Comment by humdingerb** [comment]
Fixed with #91. Thanks!
