### ISSUE TITLE
Filer crash immediately

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Filer#95]
I've built filer from the last available commit 514d5dd680a59e42f11e775124b5d8cd87cd2029

All went fine, but when I launch Filer, it will immediately crash.
I saved the debug report: http://sprunge.us/gQFA

**Comment by Giova84** [comment]
Please notice that I attempted to build it (Filer and Autofiler) by using GCC2 and GCC5.

**Comment by Giova84** [comment]
Sorry for the noise. I removed the AutoFilerFolders file (from 15 July) and now Filer starts correctly. But now, when I attempt to add folders to filer, Autofiler will crash. And then, when I quit Filer and start it again, it will crash again as before.
To start it again, I have to remove again the AutoFilerFolders file. But in facts, if I add folders to watch, AutoFiler will crash and I have to delete the AutoFilerFolders file.

Debug report for Autofiler:  http://sprunge.us/XNNI

**Comment by humdingerb** [comment]
Thanks for the report!

This is the [culprit](https://github.com/HaikuArchives/Filer/commit/514d5dd680a59e42f11e775124b5d8cd87cd2029#diff-da3380bb1f27a8865f580a85f8856f9eL87)

@owenca: reverting to `folderList->AddItem(new BStringItem(str));` fixes it.

@Giova84: Can I interest you in doing an Italian translation, see #92 ? :)

**Comment by Giova84** [comment]
Hi Humdinger, I already have a it.catkeys file (which I made today) I'd like to test it on Filer, to see if everything will look fine :-) Where I will have to place this file to see Filer translated?
I'll wait for this ticket to be fixed to build the new version, I'll check  the translation inside the app and then I will share the catkey file with you :-)

**Comment by humdingerb** [comment]
You can revert Filer's source to before the breakage with:
`
git reset --hard f2d805d91a2732d508d1a8f99e5dd2dd128cccda
`
* Put your "it.catkeys" into the sources/locale/ folder
* Open the Makefile and at "it" at LOCALES
* Do a "make" followed by "make bindcatalogs"

**Comment by Giova84** [comment]
After ```git reset --hard f2d805d91a2732d508d1a8f99e5dd2dd128cccda```  I got
```fatal: Not a git repository (or any parent up to mount point /boot)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).``` 

Obviously I miss something because I admit that I'm weak with GIT :-)

**Comment by Giova84** [comment]
After ```git reset --hard f2d805d91a2732d508d1a8f99e5dd2dd128cccda```
I got:
```fatal: Not a git repository (or any parent up to mount point /boot)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)```

I obviously miss something because I admit that I am poor with GIT :-)

**Comment by humdingerb** [comment]
Sorry, I'm not familiar with that error... A quick websearch wasn't enlightening either.

You are in Filer's folder when issueing that command? Anyway, let's wait for owenca to see if he agrees to revert that part in the code.

**Comment by Giova84** [comment]
Sorry: I'm not familiar at all with Git :-)
Hower, sure: I was in Filer's folder when issueing that command.

Anyway, to summarize the trouble: despite the fact that I deleted my old AutoFilerFolders file, I cannot add any folder to watch inside Filer: at the next run, Filer will always crash.

**Comment by humdingerb** [comment]
Yes. I think I found the breaking code change, as I referred to above.

If you cannot revert the code revision with "git reset", you can edit RefStorage.cpp directly.
Just replace the lines 85 and 86 with line 84, see:
https://github.com/HaikuArchives/Filer/commit/514d5dd680a59e42f11e775124b5d8cd87cd2029#diff-da3380bb1f27a8865f580a85f8856f9e

**Comment by Giova84** [comment]
With your suggestion to fix it, now works fine (I mean with the old AutoFilerFolders file); however when I launch Filer is still in english: I am sure that I followed everything: I edit both makefile (for Filer and Autofiler) at the line:
```LOCALES = it```
Then I run ```make && make bindcatalogs``` and was ok since I got
```for lc in it; do linkcatkeys -o objects.x86-cc2-release/Filer -s application/x-vnd.dw-Filer -tr -l $lc locales/$lc.catkeys; done```
And
```for lc in it; do linkcatkeys -o objects.x86-cc2-release/AutoFiler -s application/x-vnd.dw-AutoFiler -tr -l $lc locales/$lc.catkeys; done```

Maybe is due to the fact that I run Haiku in English?

**Comment by humdingerb** [comment]
Yes. You have to set Italian in the Locale prefs.
You normally just add "it" to the existing locales, i.e. en and de currently.
AutoFiler's makefile doesn't have to be "localized", because the it's just a daemon calling Filer, so it has no strings that need translating.

**Comment by Giova84** [comment]
Now I noticed that despite the fact that all my rules and folders are still recognized, AutoFiler no longer works: just Filer works: in fact if i drag in the dropzone a file that I know is recognized by a rule, all is ok. But AutoFiler is no longer triggered.

**Comment by humdingerb** [comment]
Make sure you have not an "old" AutoFiler running. Best remove any other Filer or AutoFiler from your system. Filer expects AutoFiler to sit in the same folder as the Filer executable. You have to build AutoFiler too with "make -f Makefile_AutoFiler". Then both Filer and Autofiler should sit in the "objects.x86-cc2-release" folder.

**Comment by Giova84** [comment]
I have the new AutoFiler running and is in the same folder of Filer; the old binaries are inside a zip file :-)

**Comment by humdingerb** [comment]
Mysterious. Are you sure AutoFiler is running? Have you checked the AutoFiler tab, the button should say "Stop AutoFiler".
I tried it and AutoFiler works here...

**Comment by Giova84** [comment]
Yeah: I can see it in the ProcessController; in the AutoFiler tab I am able to stop and start AutoFiler.
Dis you tried using old config files?

**Comment by Giova84** [comment]
I deleted again the AutoFilerFolders file, then I added again folders (well, I started by adding just one folder), and AutoFiler - the new one - still crashed...

**Comment by humdingerb** [comment]
Strange. Works here...
But you are right, when I installed the old filer package and had the settings and AutoFilerFolders created with it. The new Filer showed an empty AutoFiler tab. So that setting at least, isn't backwards compatible.

If you  add a "TRUE" at "DEBUGGER =" in the Makefiles of both Filer and AutoFiler, the stack trace is more meaningful. You have to re-make both Filer and AutoFiler. They apper in a new "debug" object folder.

**Comment by Giova84** [comment]
Done. Built both binarie with "DEBUGGER = TRUE"; however if I open the syslog file and I will look for "filer" the only entry is "KERN: debug_server: Killing team 699 (/boot/home/config/non-packaged/apps/Filer/AutoFiler)"

**Comment by humdingerb** [comment]
(/boot/home/config/non-packaged/apps/Filer/AutoFiler is the newl build one, right? Just to make sure...

You should get more info by clicking on "Save report" or what the button label is on the crash alert.

**Comment by Giova84** [comment]
Sure. Here the debug report with debug enabled: http://sprunge.us/JICM
I say a reference to RefStorage.cpp:106, AutoFiler.cpp:34 and AutoFiler.cpp:221

**Comment by humdingerb** [comment]
Thanks. Let's wait for @owenca , he's the coding boss. I just work here... :)

**Comment by Giova84** [comment]
Without your work I would have been unable to give useful (I hope) informations :-)

**Comment by owenca** [comment]
Sorry about the chaos! Hope PR #96 will take care of it.
